language: node_js
sudo: true
dist: trusty
node_js:
  - 10
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install --pure-lockfile
  - yarn global add codecov
script:
  - yarn build:proto
  - yarn build
  - yarn run test
after_success:
  - codecov
cache:
  directories:
  - "$HOME/.yarn-cache"
