language: node_js
sudo: true
dist: trusty
node_js:
  - 10
branches:
  except:
  - /^v[0-9]/
install:
  - yarn install --pure-lockfile
  - yarn global add codecov
script:
  - yarn bootstrap
  - yarn run test
after_success:
  - codecov
deploy:
  provider: script
  script: yarn publish
  on:
    branch: master
cache:
  directories:
  - "$HOME/.yarn-cache"
